# Generated by Django 4.2.25 on 2025-10-28 09:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'Case A'), ('B', 'Case B'), ('C', 'Case C'), ('D', 'Case D'), ('E', 'Case E'), ('F', 'Case F'), ('G', 'Case G'), ('H', 'Case H'), ('J', 'Case J'), ('K', 'Case K'), ('L', 'Case L'), ('M', 'Case M'), ('N', 'Case N'), ('P', 'Case P'), ('Q', 'Case Q')], max_length=1, unique=True)),
                ('year', models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(2000)])),
                ('description', models.TextField(blank=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('total_cars', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Case Mix',
                'verbose_name_plural': 'Case Mixes',
                'ordering': ['year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color_theme', models.CharField(default='#ff3d3d', help_text='Hex color code', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Series',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CollectorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.TextField(blank=True)),
                ('years_collecting', models.IntegerField(default=0)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('favorite_series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.series')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casting_name', models.CharField(max_length=200)),
                ('number', models.CharField(help_text='e.g., 1/250, 01/10', max_length=20)),
                ('year', models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(1968)])),
                ('color', models.CharField(max_length=100)),
                ('treasure_hunt', models.CharField(choices=[('NONE', 'Regular'), ('TH', 'Treasure Hunt'), ('STH', 'Super Treasure Hunt'), ('CHASE', 'Chase Edition')], default='NONE', max_length=10)),
                ('manufacturer', models.CharField(default='Mattel', max_length=100)),
                ('scale', models.CharField(default='1:64', max_length=20)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('condition', models.CharField(choices=[('MINT', 'Mint in Package'), ('OPENED', 'Opened/Loose'), ('DAMAGED', 'Package Damaged')], default='MINT', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/%Y/')),
                ('notes', models.TextField(blank=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_for_trade', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='collection.case')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='collection.series')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'ordering': ['-created_at'],
            },
        ),
    ]
